export enum AuditAction {
  VIEW_CITIZEN_PROFILE = 'VIEW_CITIZEN_PROFILE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  VIEW_FILE = 'VIEW_FILE',
  SUBMIT_BULLETIN_REQUEST = 'SUBMIT_BULLETIN_REQUEST',
  PROCESS_PAYMENT = 'PROCESS_PAYMENT',
  GENERATE_BULLETIN = 'GENERATE_BULLETIN',
  SUBMIT_CONVICTION = 'SUBMIT_CONVICTION',
  VALIDATE_CONVICTION = 'VALIDATE_CONVICTION',
  REJECT_CONVICTION = 'REJECT_CONVICTION',
  PROPOSE_IDENTITY_EDIT = 'PROPOSE_IDENTITY_EDIT',
  VALIDATE_IDENTITY_EDIT = 'VALIDATE_IDENTITY_EDIT',
  OPEN_REVIEW_TICKET = 'OPEN_REVIEW_TICKET',
  ROUTE_REVIEW_TICKET = 'ROUTE_REVIEW_TICKET',
  CORRECT_CONVICTION_FROM_TICKET = 'CORRECT_CONVICTION_FROM_TICKET',
  MAINTAIN_CONVICTION_FROM_TICKET = 'MAINTAIN_CONVICTION_FROM_TICKET',
  CLOSE_REVIEW_TICKET = 'CLOSE_REVIEW_TICKET',
  VIEW_USER_PROFILE = 'VIEW_USER_PROFILE',
  UPDATE_USER = 'UPDATE_USER',
  TOGGLE_USER_ACTIVE = 'TOGGLE_USER_ACTIVE',
  CREATE_CITIZEN_BY_ADMIN = 'CREATE_CITIZEN_BY_ADMIN',
}

export interface AuditLogEntry {
  id: string;
  timestamp: string;
  userId: string | null;
  userEmail: string | null;
  userRole: string | null;
  action: AuditAction;
  targetType?: string;
  targetId?: string;
  details?: string;
}
